language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
#install: "pip install -r requirements.txt --use-mirrors"
#install:
install:
  - "pip install . "
script:
### test are done in the install part ! 
 - "echo 1"
