#!/usr/bin/env python
from archery.bow import Hankyu as _dict
from archery.barrack import bowyer
from yahi import notch, shoot, ToxicSet
from json import loads
from datetime import datetime
import re

######################## Setting UP ##################################
# parsing command line & default settings. Return a not fully qualified object
context=notch("yahi/test/auth.log",
    off="user_agent",
    log_format="custom",
#    diagnose="match",
    output_format="json",
    date_pattern="%b %d %H:%M:%S", 
    log_pattern="""^(?P<datetime>[^\ ]+\s{1,2}\d{1,2}\s\d{2,2}:\d{2,2}:\d{2,2})\s
(?P<nawak>[^:]+):\s
Invalid\ user\ (?P<user>.*?)\s
from\ (?P<ip>\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})$""")
#May 20 12:14:15 lupin sshd[36291]: Invalid user dave from 69.60.114.57

date_formater= lambda dt :"%s-%s-%s" % ( dt.year, dt.month, dt.day)
##### OKAY, now we can do the job ########################################## 
context.output(
    shoot(
        context,
        lambda data: _dict({
            "black_list" : ToxicSet([ data["ip"] ]),
            "by_country" : _dict({ data["country"] : 1 }),
            "date" : _dict({ date_formater(data["_datetime"]) : 1 }),
            "by_ip" : _dict({ data["ip"] : 1 }),
            "by_user" : _dict({ data["user"] : 1 }),
        })
    ),
    indent=4,
    default=ToxicSet.to_json
)
