#!/usr/bin/env python
from archery.bow import Hankyu 
from yahi import Yahi
from datetime import datetime

######################## Setting UP ##################################
# parsing command line & default settings. Return a not fully qualified object
yahi=Yahi()#cache_size= 1000, silent=True, output_format='csv')
##### OKAY, now we can do the job ########################################## 
date_formater= lambda dt :"%s-%s-%s" % ( dt.year, dt.month, dt.day)
#def include(data):
#    include=True
#    include&= not data["ip"].startswith("192.168.0.35")
#    include&= not "munin" in data["uri"] 
#    include&= not "munin" in data["referer"]
#    include&= datetime(2012,05,4,0,0,0) < data["_datetime"]
#    return include
#yahi.data_filter=include


yahi.output(
    yahi.shoot(
        lambda data : Hankyu({
            'by_country': Hankyu({data['country']: 1}),
            'by_date': Hankyu({date_formater(data['_datetime']): 1 }),
            'by_hour': Hankyu({data['_datetime'].hour: 1 }),
            'by_os': Hankyu({data['ua_os_name']: 1 }),
            'by_dist': Hankyu({data['ua_dist_name']: 1 }),
            'by_browser': Hankyu({data['ua_browser_name']: 1 }),
            'by_ip': Hankyu({data['ip']: 1 }),
            'by_status': Hankyu({data['status']: 1 }),
            'by_url': Hankyu({data['uri']: 1}),
            'by_agent': Hankyu({data['agent']: 1}),
            'by_referer': Hankyu({data['referer']: 1}),
            'ip_by_url': Hankyu({data['uri']: Hankyu( {data['ip']: 1 })}),
            'bytes_by_ip': Hankyu({data['ip']: int(data['bytes'])}),
            'week_browser' : Hankyu({data['_datetime'].weekday():
                Hankyu({data["ua_browser_name"] :1 })}),
            'total_line' : 1,
        }),
    )
)
#print yahi.log["error"]
#print yahi.cachemaker._cache
yahi.cachemaker.clear()
