# -*- coding: utf-8 -*-
#
# yahi documentation build configuration file, created by
# sphinx-quickstart on Thu Jul 19 13:31:16 2012.
#
# This file is execfile()d with the current directory set to its containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys, os

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#sys.path.insert(0, os.path.abspath('.'))

# -- General configuration -----------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be extensions
# coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
extensions = [
    "sphinx.ext.extlinks",
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix of source filenames.
source_suffix = '.rst'

# The encoding of source files.
#source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'yahi'
copyright = u'2012, julien tayon'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = "0.4"
# The full version, including alpha/beta/rc tags.
release = '0.4.1'

exclude_patterns = []

pygments_style = 'sphinx'

# A list of ignored prefixes for module index sorting.
#modindex_common_prefix = []


# -- Options for HTML output ---------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = 'alabaster'


extlinks = {
    "git_tag": ("https://github.com/sphinx-doc/alabaster/tree/%s", "%s"),
    "bug": ("https://github.com/sphinx-doc/alabaster/issues/%s", "#%s"),
    "feature": ("https://github.com/sphinx-doc/alabaster/issues/%s", "#%s"),
    "issue": ("https://github.com/sphinx-doc/alabaster/issues/%s", "#%s"),
}

#html_sidebars = {'**': ['fulltoc.html', 'relations.html', 'sourcelink.html', 'searchbox.html']}
html_sidebars = {
    '**': [
        'about.html',
        'searchfield.html',
        'fulltoc.html',
        'relations.html',
        'donate.html',
    ]
}

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
html_theme_options = {
    "github_user":  "jul",
    'sidebar_width': '22em',
        'body_max_width' : 'none',
    'page_width': '70em',
    'fixed_sidebar' : True,
    "logo" : "lol.png",
    'logo_name': True,
    "github_repo": "yahi",
    "github_banner" : True,
    'github_button': False,

    }


# Add any paths that contain custom themes here, relative to this directory.
#html_theme_path = []

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
#html_title = None

# A shorter title for the navigation bar.  Default is the same as html_title.
#html_short_title = None

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
#html_logo = None

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
#html_favicon = None

html_static_path = ['_static']


htmlhelp_basename = 'yahidoc'


latex_elements = {
}

latex_documents = [
  ('index', 'yahi.tex', u'yahi Documentation',
   u'julien tayon', 'manual'),
]

man_pages = [
    ('index', 'yahi', u'yahi Documentation',
     [u'julien tayon'], 1)
]


texinfo_documents = [
  ('index', 'yahi', u'yahi Documentation',
   u'julien tayon', 'yahi', 'One line description of project.',
   'Miscellaneous'),
]

