#!/usr/bin/env python
from archery import mdict
from yahi import notch, shoot
from datetime import datetime


context=notch()

date_formater= lambda dt :"%s-%s-%s" % ( dt.year, dt.month, dt.day)
context.output(
    shoot(
        context,
        lambda data : mdict({
            'by_country': mdict({data['_country']: 1}),
            'date_hit': mdict({data['_date']: 1 }),
            'date_bandwidth': mdict({data['_date']: int(data["bytes"]) }),
            'hour_hit': mdict({data['_datetime'].hour: 1 }),
            'hour_bandwidth': mdict({data['_datetime'].hour: int(data["bytes"]) }),
            'by_os': mdict({data['_platform_name']: 1 }),
            'by_scheme' :  mdict( { data["scheme"] : 1 }),
            'by_scheme_by_bandwidth' :  mdict( { data["scheme"] :  int(data["bytes"])}),
            'by_dist': mdict({data['_dist_name']: 1 }),
            'by_browser': mdict({data['_browser_name']: 1 }),
            'by_bandwidth_by_browser': mdict({data['_browser_name']: int(data["bytes"]) }),
            'by_ip': mdict({data['ip']: 1 }),
            'by_bandwidth_by_ip': mdict({data['ip']: int(data["bytes"]) }),
            'by_status': mdict({data['status']: 1 }),
            'by_url': mdict({data['uri']: 1}),
            'by_agent': mdict({data['agent']: 1}),
            'by_referer': mdict({data['referer']: 1}),
            'date_dayofweek_hit' : mdict({data['_datetime'].weekday(): 1 }),
            'weekday_browser' : mdict({data['_datetime'].weekday():
                mdict({data["_browser_name"] :1 })}),
            'total_line' : 1,
        }),
    ),
)
