#!/usr/bin/env python
from archery.bow import Hankyu as _dict
from yahi import notch, shoot
from datetime import datetime


context=notch()

date_formater= lambda dt :"%s-%s-%s" % ( dt.year, dt.month, dt.day)
context.output(
    shoot(
        context,
        lambda data : _dict({
            'by_country': _dict({data['_country']: 1}),
            'date_hit': _dict({date_formater(data['_datetime']): 1 }),
            'date_bandwidth': _dict({date_formater(data['_datetime']): int(data["bytes"]) }),
            'hour_hit': _dict({data['_datetime'].hour: 1 }),
            'hour_bandwidth': _dict({data['_datetime'].hour: int(data["bytes"]) }),
            'by_os': _dict({data['_platform_name']: 1 }),
            'by_dist': _dict({data['_dist_name']: 1 }),
            'by_browser': _dict({data['_browser_name']: 1 }),
            'by_bandwidth_by_browser': _dict({data['_browser_name']: int(data["bytes"]) }),
            'by_ip': _dict({data['ip']: 1 }),
            'by_bandwidth_by_ip': _dict({data['ip']: int(data["bytes"]) }),
            'by_status': _dict({data['status']: 1 }),
            'by_url': _dict({data['uri']: 1}),
            'by_agent': _dict({data['agent']: 1}),
            'by_referer': _dict({data['referer']: 1}),
            'ip_by_url': _dict({data['uri']: _dict( {data['ip']: 1 })}),
            'bytes_by_ip': _dict({data['ip']: int(data['bytes'])}),
            'date_dayofweek_hit' : _dict({data['_datetime'].weekday(): 1 }),
            'weekday_browser' : _dict({data['_datetime'].weekday():
                _dict({data["_browser_name"] :1 })}),
            'total_line' : 1,
        }),
    ),
)
