#!/usr/bin/env python
# -*- encoding: utf-8 -*-
"""
All in one maker
================

Generates a all in one yahi output web page from the stats given in
its json form as the first parameter.

Outputs the result in the local file aio.html

"""
from sys import argv
from yahi import DIR
from yahi.template import template
from os import path
from html import escape

usage = lambda : print(__doc__) or exit(1)

data_location="./data.js"
try:
    data_location = argv[1]
except:
    pass

        
with open(data_location) as f:
    DATA=f.read()
    res = template.replace("{{DATA}}", escape(DATA))

with open(path.join(DIR,'jquery-3.7.1.min.js.py')) as f:
    JQUERY=f.read()
    res = res.replace("{{JQUERY}}", JQUERY)

with open(path.join(DIR,'d3.min.js.py'), encoding='utf-8') as f:
    D3=f.read()
    res = res.replace("{{D3}}", D3)

    with open("aio.html", "w", encoding='utf-8') as h:
        h.write(res)


